# a good example is: https://github.com/boostorg/hana/blob/master/.travis.yml
language: cpp
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
    - os: linux
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      dist: trusty
      compiler: clang
      osx_image: xcode7
    - os: osx
      dist: trusty
      compiler: clang
      osx_image: xcode7.1
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - echo $CXX
  - which $CXX
  - which $CC
  - $CXX --version
  - python --version
  - git submodule update --init
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX_COPY=$CXX;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      if [$CXX_COPY == "clang++"]; then
          sudo apt-get install clang-3.6 lldb-3.6;
          export CXX='clang++-3.6';
          export CC='clang-3.6';
      else
          sudo apt-get -qq install g++-5 gdb;
          export CXX='g++-5';
          export CC='gcc-5';
      fi
      sudo apt-get -qq install ninja-build;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install ninja;
    fi
  - $CXX --version
  - which $CXX
  - which $CC
before_script: ls
script:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
        if [$CXX == "clang++-3.6"]; then
            python build.py -Dasan=1 -Dlsan=1;
        else
            python build.py;
        fi
    else
        python build.py -Dasan=1 -Dlsan=1;
    fi
  - ./out/Debug/test
  - ./out/Release/test
branches:
  only:
    - master
env:
  global:
    - LANG="en_US.UTF-8"
os:
  - linux
  - osx
