language: cpp
compiler:
  - clang
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - $CXX --version
  - python --version
  - git submodule update --init
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ] && [$CXX == "clang++"]; then
      sudo deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
      sudo deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
      sudo deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-get -qq install clang-3.6 lldb-3.6;
      export CXX='clang++-3.6';
    else
      sudo apt-get -qq install g++-4.8;
      export CXX='g++-4.8';
    fi
before_script: ls
script:
  - python build.py
  - ./out/Debug/test
  - ./out/Release/test
branches:
  only:
    - master
env:
  global:
    - LANG="en_US.UTF-8"
os:
  - linux
  - osx
