language: cpp
compiler:
  - clang
  - gcc
before_install:
  - echo "$LANG"
  - echo "$LC_ALL"
  - echo "`$CXX --version`"
  - echo "`python --version`"
  - git submodule update --init
before_script: ls
script:
  - python build.py
  - out/Debug/test
  - out/Release/test
branches:
  only:
    - master
env:
  global:
    - LANG="en_US.UTF-8"
os:
  - linux
  - osx
