# a good example is: https://github.com/boostorg/hana/blob/master/.travis.yml
language: cpp
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
    - os: linux
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
      osx_image: xcode7
    - os: osx
      compiler: clang
      osx_image: xcode7.1
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - echo $CXX
  - which $CXX
  - which $CC
  - $CXX --version
  - python --version
  - git submodule update --init
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]] ; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install ninja-build;
      sudo deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main;
      sudo deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty main;
      sudo deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main;
      sudo deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main;
      sudo apt-get -qq install -y clang-3.6 lldb-3.6;
      export CXX=clang++-3.6;
      export CC=clang-3.6;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]] ; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install -y ninja-build;
      sudo apt-get -qq install -y g++-5;
      export CXX=g++-5;
      export CC=gcc-5;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      brew install ninja;
    fi
  - $CXX --version
  - which $CXX
  - which $CC
before_script: ls
script:
  - python build.py -Dasan=1 -Dlsan=1
  - ./out/Debug/test
  - ./out/Release/test
branches:
  only:
    - master
env:
  global:
    - LANG="en_US.UTF-8"
os:
  - linux
  - osx
