language: cpp
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
  include:
    - os: osx
    env: COMPILER=clang++-3.6
      addons: &clang36
        apt:
          packages: ["clang-3.6", "valgrind"]
          sources: *sources
      env: xcode7
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - $CXX --version
  - python --version
  - git submodule update --init
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install ninja-build;
      if [$CXX == "clang++"]; then
          sudo deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
          sudo deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
          sudo deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main
          wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-get -qq install clang-3.6 lldb-3.6;
          export CXX='clang++-3.6';
      else
          sudo apt-get -qq install g++-5;
          export CXX='g++-5';
      fi
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install ninja;
      if [$CXX == "clang++"]; then
          export CXX='clang++';
      else
          export CXX='g++-4.9';
      fi
    fi
  - $CXX --version
before_script: ls
script:
  - python build.py
  - ./out/Debug/test
  - ./out/Release/test
branches:
  only:
    - master
env:
  global:
    - LANG="en_US.UTF-8"
os:
  - linux
  - osx
